### ISSUE TITLE
Deep links to "Migration from zgen" section seem to be broken (or poorly supported in browsers?) as parent "Installation" section is initially collapsed

### ISSUE THREAD

**Issue by gimbo** [jandamm/zgenom#114]
Subject line says it all, really: near the start of the README there's a zgen "migration guide" link, but that section seems to have been removed from the README? As a zgen user who's considering migrating, I'd be interested to know what was there, particularly if there are any gotchas... 😄

**Comment by gimbo** [comment]
Ah, I've just realised it's *not* a dead link, but that the migration guide is now in the initially-collapsed "Installation" section (done via a `<details>` block, it seems), which in my browser at least (Chrome on macOS) means the link doesn't seem to go anywhere unless that section is already expanded (and links from outside, e.g. [this zgen issue comment](https://github.com/tarjoilija/zgen/issues/123#issuecomment-733178282) also just come straight to the top of the README, not the actual section we're interested in.

I'll update the issue description accordingly.

**Comment by jandamm** [comment]
Yes, probably makes sense to move that part out of the details section 👍

**Comment by jandamm** [comment]
Should be fixed now. Thanks again for reporting 👍
