### ISSUE TITLE
Consider using tags and versions - for easier updating to stable releases

### ISSUE THREAD

**Issue by OdinsHat** [jandamm/zgenom#120]
Some package managers require versions to be able to install packages from Gtihub. You would be helping a lot if you started to use tags and release version numbers.

**Comment by jandamm** [comment]
Do you mean that zgenom is tagged or that you can pin a plugin to a specific tag?

**Comment by OdinsHat** [comment]
The repo itself is tagged. E.g. `git tag -a v1.0 -m "Latest Stable Release"`

**Comment by jandamm** [comment]
Ah, I see.
I consider everything merged into main as a stable release.

What package manager are you talking about. What is your use case?
