### ISSUE TITLE
zsh option 'noclobber' prevents autoupdate log from being updated

### ISSUE THREAD

**Issue by henk84** [jandamm/zgenom#129]
```
__zgenom_autoupdate_log:7: file exists: /home/henk/.zgenom/.last_autoupdate_log
```

AFAIK this might be caused by zsh’s `noclobber` option being set.
zgenom might have to unset that when it tries to overwrite the logfile.

**Comment by jandamm** [comment]
Should be fixed now, @henk84.
Thanks for reporting 👍
