### ISSUE TITLE
Pin to a commit

### ISSUE THREAD

**Issue by musjj** [jandamm/zgenom#144]
It'd be useful if we can pin plugins to a specific commit. I had some plugins break because of an update and I now have no way to pin or rollback to a working commit.

**Comment by jandamm** [comment]
Yes, that's currently not possible.
It's possible to specify a branch or tag but not a commit.

Currently `zgenom` only clones the last commit (`--depth=1`) of the specified branch. So simply checking out the commit after cloning wouldn't work.
Also updating the plugin must be prevented.

I'll add it as a feature idea to my to do list but it's not as trivial as one might think.

**Comment by hauntsaninja** [comment]
Note you can do something like this (note sha1 must be a full hash)
```
git init
git remote add origin <url>
git fetch --depth 1 origin <sha1>
git checkout FETCH_HEAD
```
https://stackoverflow.com/a/43136160

**Comment by jandamm** [comment]
Thanks @hauntsaninja! 
I found a similar snippet while working on a CI pipeline but haven't found the time to implement it yet.
It might need some tweaks to properly work when updating (or rather not updating).
