### ISSUE TITLE
Slow startup times via `zgenom ohmyzsh`

### ISSUE THREAD

**Issue by V4G4X** [jandamm/zgenom#147]
I use zgenom to load all my zsh plugins(ohmyzsh and others).  
I do this to keep my shell loading time to a minimum.

For e.g

```sh
zgenom ohmyzsh
    
zgenom ohmyzsh plugins/sudo
zgenom ohmyzsh plugins/git
zgenom ohmyzsh plugins/cp
zgenom ohmyzsh plugins/aws
zgenom ohmyzsh plugins/golang
zgenom ohmyzsh plugins/copypath
```

The issue is, the first `zgenom ohmyzsh` is doubling my start-up time. From 0.6s to 1.2s.

I can tell my experience differs on commenting that first line as tabbing on multiple options doesn't work like it did before.  
Is there a list of features that you get on running `zgenom ohmyzsh`?

**Comment by jandamm** [comment]
My guess would be a recent change in ohmyzsh. I didn't change anything in the ohmyzsh code for a long time.
It's actually not much more than `zgenom load` the ohmyzsh repo prefilled.

`zgenom ohmyzsh` will when not provided a path (e.g. `plugins/sudo`) will do the same as `zgenom ohmyzsh oh-my-zsh.sh`.
So it loads whatever ohmyzsh will load by default.

**Comment by jandamm** [comment]
Hey @V4G4X have you had the time to investigate this?
Otherwise I'd soon close this issue.
