### ISSUE TITLE
Unable to dynamically load a plugin

### ISSUE THREAD

**Issue by V4G4X** [jandamm/zgenom#150]
So I have a notify plugin I want to be loaded only in case of a Tmux session or a Vim session. (Because I use iTerm's inbuilt notifier in other cases)

I tried loading it through an IF statement (outside of the `if ! zgenom saved; then ... fi` block):
```sh
if [[ $TMUX ]] || [[ $VIMRUNTIME ]]; then
    zgenom load MichaelAquilina/zsh-auto-notify
fi
```

I know the conditions are working because I checked with echo. It printed only when appropriate. 

I'm sure I'm not using `zgenom load` correctly. Any help?

**Comment by jandamm** [comment]
Hey @V4G4X,

this should actually work.
`zgenom load` does exactly the same when called like this.

Is it working when you put it inside the if block?

Would you mind testing it with another plugin?

You could also try to always add but disable `zsh-auto-notify` in those cases. Might even be faster than dynamically loading.

**Comment by V4G4X** [comment]
Really sorry @jandamm. Turns out I was not testing it properly.  
The notification only came on tasks running longer than 15 seconds.  

But I still want to know how to
> disable zsh-auto-notify in those cases

Could you let me know how to do that? 
And why do you think it will be faster than dynamically loading?

**Comment by jandamm** [comment]
You can always run `disable_auto_notify` to disable notifications. See https://github.com/MichaelAquilina/zsh-auto-notify#temporarily-disabling-notifications.

`zgenom` is loading itself lazily. This means it loads just the bare minimum when it has a saved init file and just loads the cached file.
When you run `zgenom load` `zgenom` has to load itself full.

So the question is whether loading `zgenom` fully or loading and disabling the notifications is faster. This is something you would have to try.

**Comment by V4G4X** [comment]
Thanks!

There was no noticeable difference to my naked eye,
so did it as per your suggestion anyway.
