### ISSUE TITLE
Add support for "main" branch instead of "master"

### ISSUE THREAD

**Issue by jandamm** [jandamm/zgenom#16]
Many repositories move from `master` to `main`.
So hardcoding `master` as default branch isn't really future proof.

Taken over from #13

**Comment by jandamm** [comment]
When no branch is specified for `zgen load` the repository should be cloned without a branch.
Then ideally on zgen update I check for those repositories if the default branch has changed and would start using the new branch. (After cloning you can ask a git remote for its head branch)

**Comment by jandamm** [comment]
Following the remotes head is doable. But following a remotes head for a shallow clone is a different thing.
You have to fetch the branch first. Since you don't know the name of the branch all branches would have to be fetched.

Another option is to use `git remote show origin` and hope that the format is consistent between versions of git. Also this could result in ambiguous results.

Need to test a bit more.
Fallback could be to delete the folder an clone again when detecting a change of head.

**Comment by unixorn** [comment]
Maybe do shallow clones with no branch specified unless the user configures a specific branch? That should get the default branch without having to do any parsing.

Once you have cloned you can find it with `git remote show origin | awk '/HEAD branch/ {print $3}'`

**Comment by jandamm** [comment]
I got something working with `git remote set-head`.
Currently testing it and I'll push it soon 👍

**Comment by unixorn** [comment]
Neat, looking forward to it.
