### ISSUE TITLE
Allowing for default branch seems to have broken oh-my-zsh

### ISSUE THREAD

**Issue by steeef** [jandamm/zgenom#21]
Just ran `zgen update` and pulled in the most recent commits, including the "use default branch instead of master" change. Now I'm seeing these errors anytime I create a new shell:

```
/Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-___/oh-my-zsh.sh:source:12: no such file or directory: /Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-master/tools/check_for_upgrade.sh
/Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-___/oh-my-zsh.sh:cd:63: no such file or directory: /Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-master
/Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-___/oh-my-zsh.sh:source:74: no such file or directory: /Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-master/lib/compfix.zsh
/Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-___/oh-my-zsh.sh:76: command not found: handle_completion_insecurities
/Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-___/oh-my-zsh.sh:100: no matches found: /Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-master/lib/*.zsh
/Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-___/plugins/kubectl/kubectl.plugin.zsh:5: no such file or directory: /Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-master/cache/kubectl_completion
```

I think this is coming from `oh-my-zsh`'s default settings:

```
❯ echo $ZSH
/Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-master
❯ echo $ZSH_CACHE_DIR
/Users/sprice/.zgenom/sources/ohmyzsh/ohmyzsh-master/cache
```

Relevant lines from my zgen setup script:

```
zgen oh-my-zsh
zgen oh-my-zsh plugins/kubectl
```

any advice on how to avoid? Should I specify the `master` branch for `oh-my-zsh` explicitly? How do I do that?

**Comment by jandamm** [comment]
Sorry my bad. I'll see that I get a fix out today.

In the meantime you could try to set this before you source zgenom: `ZGEN_OH_MY_ZSH_BRANCH=___`

**Comment by jandamm** [comment]
@steeef I think I've fixed it.
Could you please switch from `main` to `Fix-oh-my-zsh-prezto-default-branches` to verify.
When you switched branches, run `zgen reset` and start a new shell the issues should be gone 👍

**Comment by steeef** [comment]
@jandamm Yup, that did it. `oh-my-zsh` loading works fine now. Thanks!

**Comment by jandamm** [comment]
Thanks for the confirmation 👍
