### ISSUE TITLE
'zgen-compile' fails with 'dotbare' plugin

### ISSUE THREAD

**Issue by kylo252** [jandamm/zgenom#45]
Hey,

First of all, thanks for the hardwork! I've just been trying `zgenom` after switching from `Antibody` and I'm really happy so far. 

When adding:
```shell
	zgenom load kazhala/dotbare
```
and then when I try to load it:
```shell
❯ zgenom reset
-- zgenom: Deleting `/home/$USER/.local/share/zgenom/init.zsh` ...
❯ zgenom save
-- zgenom: Creating `/home/$USER/.local/share/zgenom/init.zsh` ...
-- zgenom: Initializing completions ...
-- zgenom: Compiling files ...
-zgen-compile:119: parse error near `\n'
-zgen-compile:zcompile:3: can't read file: /home/$USER/.local/share/zgenom/kazhala/dotbare/___/helper/preview.sh
```

The weird thing is that it seems that `dotbare` works fine regardless of that initial error. 

P.s: It works out of the box with `Antibody`.

**Comment by jandamm** [comment]
Hey @kylo252,

thank you for reporting this.
Your observation is right, the plugin just works flawlessly.

The issue you're seeing indicates that one file (`kazhala/dotbare/___/helper/preview.sh`) can't be compiled.
This results in using the not compiled version instead. (So no issue when using the plugin)

As far as I know `Antibody` didn't compile the source code. 
I tested it about a year ago and it made zgenom about 25% faster (back then zgenom was zgen + some scripts).

I'll have a look what I can do to suppress this error message 👍

Cheers Jan
