### ISSUE TITLE
Any workaround for when zgenom source dir is immutable?

### ISSUE THREAD

**Issue by martinbaillie** [jandamm/zgenom#57]
I try to keep a deterministic OS userspace with Nix/NixOS but found zgenom wants to write the compiled versions of itself to the source directory.
```
-zgen-compile:zcompile:3: can't write zwc file: /nix/store/41nvcwaknvb2n051g20aq48pkf0mw1cj-source/zgenom.zsh.zwc
-zgen-compile:zcompile:3: can't write zwc file: /nix/store/41nvcwaknvb2n051g20aq48pkf0mw1cj-source/zgen.zsh.zwc
```
Perhaps it needs to be like this but just thought I'd check if there was any workaround for compilation when the zgenom source directory is immutable?

**Comment by jandamm** [comment]
As far as I know the only way to use complied files in zsh is when they are stored right next to the original file.
This is also the naming pattern `zcompile` uses.

`a/b/c.zsh` -> `a/b/c.zsh.zwc`

If you then source `a/b/c.zsh` zsh will check if the compiled file is newer and then source accordingly.

So the source directory would need to be mutable until the compilation is done.
As this also only happens once per update it could be doable.
Zgenom treats the sources dir as immutable until you call `zgenom reset` or `zgenom update` (which calls `zgenom reset`)

I haven't really used Nix before but like the idea. If there's anything I can do to better support it please let me know.

**Comment by martinbaillie** [comment]
Thanks for the prompt and detailed reply. Makes sense to me.

**Comment by jandamm** [comment]
Would it make sense to disable compiling in this case?

Is there a step where you can run custom scripts in your Nix file before the folder is immutable?
Running `zgenom compile $ZGEN_DIR` from there should work.

**Comment by martinbaillie** [comment]
Hey sorry I missed this. It is what I ended up doing 👍🏻

**Comment by jandamm** [comment]
In its current form zgenom will still compile `$ZGEN_DIR`. 
But since you've compiled it before it won't need to write any new file.

Should we add `ZGENOM_NO_COMPILE`?
