### ISSUE TITLE
Is there a way to load only completion files?

### ISSUE THREAD

**Issue by QuarticCat** [jandamm/zgenom#82]
I tried this but it seems doesn't work.

```console
$ zgenom ohmyzsh plugins/ripgrep/_ripgrep
```

**Comment by QuarticCat** [comment]
I found simply use `zgenom ohmyzsh plugins/ripgrep` can work. But it adds a lot of time.

My current usage of zgenom:

```zsh
source "$HOME/.zgenom/zgenom.zsh"
if ! zgenom saved; then
    zgenom ohmyzsh lib/completion.zsh
    zgenom ohmyzsh lib/key-bindings.zsh
    zgenom ohmyzsh lib/clipboard.zsh

    zgenom ohmyzsh plugins/extract
    zgenom ohmyzsh plugins/pip
    # zgenom ohmyzsh plugins/ripgrep
    # zgenom ohmyzsh plugins/rust
    # zgenom ohmyzsh plugins/docker
    # zgenom ohmyzsh plugins/docker-compose

    zgenom load romkatv/powerlevel10k powerlevel10k
    zgenom load junegunn/fzf shell/key-bindings.zsh
    zgenom load Aloxaf/fzf-tab
    zgenom load zdharma-continuum/fast-syntax-highlighting
    zgenom load zsh-users/zsh-autosuggestions
    zgenom load zsh-users/zsh-history-substring-search
    zgenom load MichaelAquilina/zsh-you-should-use
    zgenom load hlissner/zsh-autopair

    zgenom save
fi
```

Uncomment those lines will almost double the start time of zsh. It's weird since they are just several completion files. In comparison, I used to use zinit, here is the code https://github.com/QuarticCat/dotfiles/blob/main/dot_zshrc#L14 . Deleting those completions basically reduces no time.

Time consumptions are measured by `hyperfine 'zsh -ic exit'`.

**Comment by jandamm** [comment]
Hey @QuarticCat,

this is currently not supported. The assumption was that a completion file is located in a separate folder
It's true for `ripgrep`, `rust` and `docker` but `docker-compose` will also load [this](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/docker-compose/docker-compose.plugin.zsh).
I could support this but I'm not settled on an api for it:
1. `zgenom ohmyzsh plugins/docker-compose/_docker-compose`
    This would prevent sourcing files starting with `_` at all. But would need changes in `ohmyzsh` and `load`.
2. `zgenom ohmyzsh plugins/docker-compose --completion-only`
    Maybe not clear enough?
3. `zgenom completion plugins/docker-compose` (or `fpath` instead of `completion`)
    Would add two new apis since it must work for `ohmyzsh` and `load`.

As to the mentioned performance issues: 
Adding those four lines and measuring them with `hyperfine` has an increase of -1 to 1 ms (where the whole startup time is ~100ms).
For `docker-compose` also a few aliases are created but this also does not seem to increase the startup time much.

At least on macOS I've seen huge differences between hyperfine runs without any changes. Here are three runs of `hyperfine` without any changes in between:
```
❯ hyperfine --warmup 1 --min-runs 50 'zsh -ic exi
t' 'zsh -ic exit' 'zsh -ic exit'
Benchmark 1: zsh -ic exit
  Time (mean ± σ):     100.3 ms ±   5.1 ms    [User: 55.4 ms, System: 41.2 ms]
  Range (min … max):    91.3 ms … 118.4 ms    50
runs

Benchmark 2: zsh -ic exit
  Time (mean ± σ):     101.2 ms ±   6.3 ms    [User: 55.7 ms, System: 41.9 ms]
  Range (min … max):    93.4 ms … 120.0 ms    50
runs

Benchmark 3: zsh -ic exit
  Time (mean ± σ):     105.7 ms ±  12.4 ms    [User: 57.7 ms, System: 44.0 ms]
  Range (min … max):    91.9 ms … 152.1 ms    50
runs

Summary
  'zsh -ic exit' ran
    1.01 ± 0.08 times faster than 'zsh -ic exit'
    1.05 ± 0.13 times faster than 'zsh -ic exit'
```

Also with separate runs I got a maximum difference of 5.9ms.

What timespan do you mean with "_it adds a lot of time_"?

**Comment by QuarticCat** [comment]
@jandamm I've uploaded my new `.zshrc` file https://github.com/QuarticCat/dotfiles/blob/a9662d9114747f1080a2fca115a077273febfe24/dot_zshrc#L14

Before and after uncomment L23-L26:

```
Benchmark 1: zsh -ic exit
  Time (mean ± σ):      41.9 ms ±   5.4 ms    [User: 31.1 ms, System: 12.8 ms]
  Range (min … max):    36.4 ms …  59.4 ms    65 runs
```

```
Benchmark 1: zsh -ic exit
  Time (mean ± σ):      86.4 ms ±   6.5 ms    [User: 64.3 ms, System: 33.9 ms]
  Range (min … max):    75.8 ms … 102.1 ms    36 runs
```

**Comment by jandamm** [comment]
Yeah, this sounds broken.
However I couldn't notice any difference when commenting in/out the four lines.
Could you try commenting everything below the zgenom if statement except the p10k line and then test again?

**Comment by QuarticCat** [comment]
### Only p10k

```zsh
source "$HOME/.zgenom/zgenom.zsh"
if ! zgenom saved; then
    zgenom load romkatv/powerlevel10k powerlevel10k

    zgenom save
fi
```

```
Benchmark 1: zsh -ic exit
  Time (mean ± σ):      17.5 ms ±   2.4 ms    [User: 11.7 ms, System: 6.8 ms]
  Range (min … max):    14.8 ms …  26.4 ms    150 runs
```

### p10k + that 4 lines

```zsh
source "$HOME/.zgenom/zgenom.zsh"
if ! zgenom saved; then
    zgenom ohmyzsh plugins/ripgrep
    zgenom ohmyzsh plugins/rust
    zgenom ohmyzsh plugins/docker
    zgenom ohmyzsh plugins/docker-compose

    zgenom load romkatv/powerlevel10k powerlevel10k

    zgenom save
fi
```

```
Benchmark 1: zsh -ic exit
  Time (mean ± σ):      59.8 ms ±   2.7 ms    [User: 42.1 ms, System: 28.0 ms]
  Range (min … max):    56.1 ms …  66.8 ms    49 runs
```

### p10k + docker-compose

```zsh
source "$HOME/.zgenom/zgenom.zsh"
if ! zgenom saved; then
    zgenom ohmyzsh plugins/docker-compose

    zgenom load romkatv/powerlevel10k powerlevel10k

    zgenom save
fi
```

```
Benchmark 1: zsh -ic exit
  Time (mean ± σ):      60.7 ms ±   2.7 ms    [User: 40.6 ms, System: 30.5 ms]
  Range (min … max):    56.0 ms …  66.4 ms    48 runs
```

**Comment by jandamm** [comment]
Could you try this:

```zsh
source "$HOME/.zgenom/zgenom.zsh"
if ! zgenom saved; then
    zgenom ohmyzsh plugins/ripgrep
    zgenom ohmyzsh plugins/rust
    zgenom ohmyzsh plugins/docker

    zgenom load romkatv/powerlevel10k powerlevel10k

    zgenom save
fi
fpath=($ZGEN_DIR/ohmyzsh/ohmyzsh/___/plugins/docker-compose $fpath)
```
If this is fast again something in [this file](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/docker-compose/docker-compose.plugin.zsh) is extremely slow on your machine.

**Comment by QuarticCat** [comment]
Yes, this is fast again.

```
Benchmark 1: zsh -ic exit
  Time (mean ± σ):      17.0 ms ±   1.8 ms    [User: 11.7 ms, System: 6.2 ms]
  Range (min … max):    14.7 ms …  27.4 ms    138 runs
```

And I find it is slowed by `docker compose`.

```
Benchmark 1: docker compose
  Time (mean ± σ):      40.7 ms ±   2.4 ms    [User: 29.4 ms, System: 20.7 ms]
  Range (min … max):    38.0 ms …  51.3 ms    64 runs
```

So I didn't meet this issue in zinit is because I wrote

```zsh
zinit as'completion' for OMZP::docker-compose/_docker-compose
```

which does not load `docker-compose.plugin.zsh`.

Is there a way to skip loading this file?

**Comment by jandamm** [comment]
Currently not but I'll add it.

In the meantime you can keep `fpath=($ZGEN_DIR/ohmyzsh/ohmyzsh/___/plugins/docker-compose $fpath)` which does basically the same.

**Comment by jandamm** [comment]
I've added this feature in #83.

You should be able to reduce the startup time again with `zgenom ohmyzsh --completion plugins/docker-compose`.

Would you mind testing it out?

**Comment by QuarticCat** [comment]
@jandamm It works pretty fine. Thank you!

```zsh
source "$HOME/.zgenom/zgenom.zsh"
if ! zgenom saved; then
    zgenom ohmyzsh lib/completion.zsh
    zgenom ohmyzsh lib/key-bindings.zsh
    zgenom ohmyzsh lib/clipboard.zsh
    zgenom load junegunn/fzf shell/key-bindings.zsh

    zgenom ohmyzsh plugins/extract
    zgenom ohmyzsh plugins/pip

    zgenom ohmyzsh --completion plugins/ripgrep
    zgenom ohmyzsh --completion plugins/rust
    zgenom ohmyzsh --completion plugins/docker
    zgenom ohmyzsh --completion plugins/docker-compose

    zgenom load romkatv/powerlevel10k powerlevel10k
    zgenom load Aloxaf/fzf-tab
    zgenom load zdharma-continuum/fast-syntax-highlighting
    zgenom load zsh-users/zsh-autosuggestions
    zgenom load zsh-users/zsh-history-substring-search
    zgenom load hlissner/zsh-autopair

    zgenom save
fi
```

```
Benchmark 1: zsh -ic exit
  Time (mean ± σ):      48.8 ms ±   4.7 ms    [User: 36.9 ms, System: 14.5 ms]
  Range (min … max):    41.7 ms …  63.9 ms    49 runs
```

**Comment by jandamm** [comment]
Alright, I'll do some further testing and merge it afterwards. 👍
